services:
  - type: web
    name: app-clima-backend
    env: node
    rootDir: .
    buildCommand: npm install --prefix backend && npm install --prefix frontend && npm run build --prefix frontend
    startCommand: cd backend && npm start
    autoDeploy: true
